version: '3'
services:
  soccer_api:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - .:/scripts
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
